### ISSUE TITLE
Release to MavenCentral

### ISSUE THREAD

**Issue by jakubmalek** [Webfleet-Solutions/assertj-async#1]
Create release v1.0.0 and publish to Maven Central repository.

**Comment by jakubmalek** [comment]
The artifact is already in
* [repo1.maven.org](https://repo1.maven.org/maven2/com/webfleet/assertj-async/)
* [search.maven.org](https://search.maven.org/search?q=a:assertj-async)

Waiting to be indexed at 
[mvnrepository.com](https://mvnrepository.com/artifact/com.webfleet/assertj-async)

**Comment by sewera** [comment]
Already indexed - [link](https://mvnrepository.com/artifact/com.webfleet/assertj-async/1.0.0).
